### PR TITLE
adding definitions for DBL_MIN/DBL_MAX for

### PR DESCRIPTION
**Pull request by lachlangrose**
Hi Mike, 
I am adding a wrapper to Surfe for LoopStructural and I had to make some changes to get it built. Rather than last time giving you an enormous number of changes in a pull request this time I'll do it sensibly!
I had to add in some macros to get DBL_MIN/MAX working on linux
There was a typo in the python bindings for SetInterfaceConstraints.
I also added a function and python bindings to evaluate the model on an array of xyz points.

### CODE REVIEW

**Comment by AndrewAnnex** [comment]
@lachlangrose I am interested in contributing fixes to get surfe working on macos, since you have got it working on linux it sounds like it should be relatively easy to update? unfortunately I don't have much experience with cmake yet but maybe you could point me in the right direction?

**Comment by lachlangrose** [comment]
@AndrewAnnex i think it should work fine on macos if you are using gcc... I'm setting up some git actions to be able to build libraries for windows/linux I can try and setup a mac one if you want?

**Comment by AndrewAnnex** [comment]
Ok I’ve been using cling through CLion IDE so I’ve run into issues with trying to patch the cmake file, that would be great and I’m happy to test things locally 

-Andrew Annex

**Comment by MichaelHillier** [comment]
Hey Lachlan,

I looked at these changes. Tested them on windows and everything is good. I added a local commit to this pull request that parallelizes your api function you added Surfe_API::EvaluateInterpolantAtPoints(const MatrixXd &locations) which will significantly speed evaluation. I had to change the functions return type to VectorXd instead of a std::vector<double> because of the parallelization change. This was tested and working on Windows.

Disclaimer: I am a noob when it comes to managing pull requests. I tried pushing my local commit onto the pull request. I pushed to https://github.com/Loop3D/surfe.git on master. I thought I would see those changes here in the pull request, but I don't. Not sure if I messed anything up. You can see my added changes on https://github.com/Loop3D/surfe.git - master

**Comment by lachlangrose** [comment]
Hey Mike,

I think you should be able to merge the changes into your branch. What you have done is added stuff to my version - i think we should keep your branch as the true surfe version..... 

Also perhaps you could include my git actions that build surfe for ubuntu and windows and upload the attributes to a release. This should make distributing easy.

Thanks for adding the parallelization!

Cheers

**Pull request merged**
