### PR TITLE
Adding setup.py for easy python installation

### PR DESCRIPTION
**Pull request by lachlangrose**

### CODE REVIEW

**Comment by Simon-Lopez** [comment]
Hello @lachlangrose,
Have you considered using https://scikit-build.readthedocs.io/en/latest/?
After trying several options I found it very usefull.
You can find an example of setup.py here:
https://github.com/BRGM/MeshTools/blob/master/setup.py

**Comment by lachlangrose** [comment]
Hi Simon,

No I haven't seen that before! Thanks for pointing it out! It looks like a
really good option.

Lachlan

**Comment by MichaelHillier** [comment]
I've tried building the binaries using your setup.py  file you created (thanks very much btw) but I was not able to successfully build them. Below is a screenshot of my python terminal after typing `python setup.py install`:

image

The error is with Eigen3 (a dependency - linear algebra library). I've tried installing the eigen3 (via - `conda install -c omnia eigen3` ) in my python environment but I still get the same error. Did you have any trouble with this on linux?

On Windows, when I use CMake to setup my Visual Studio project so that I can compile my library I do have to specify the location of Eigen3 on my hard drive. You think that they same would be needed for the python setup.py install? Ideally, setup.py would find these installed packages and setup all the required include directories, and if these packages were not installed it would download and install them. 

I also initially had an error related to python not being able to find cmake but that error was resolved by installing cmake on my python environment.

**Comment by lachlangrose** [comment]
For the github actions I wrote a while ago to compile the code I changed eigen to be included through a submodule in git. You might need to run 

github submodule init
github submodule update 

This will clone the pybind11 and eigen files into the local directories. If you've done that, I'm not sure....

**Comment by MichaelHillier** [comment]
pybind11 was cloned, but looks like eigen files were not cloned. Unfortunately, after running the submodule commands I still get the same error. Will look into further...

**Comment by lachlangrose** [comment]
I just tried on my windows computer and have a similar issues I was missing
the flag which specifies where eigen is. But now I am having an issue with
windows not finding the dll so i'll look at that today and fix it up!

**Comment by MichaelHillier** [comment]
With the latest changes I've been able to successfully install surfe for python on Windows. Will merge with master. This will now let us create a conda-forge distribution.

**Pull request merged**
